//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeedData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.SeedData", typeof(SeedData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Name&quot;:&quot;Жеравна - архитектурен резерват&quot;,
        ///      &quot;Description&quot;:&quot;Село Жеравна е разположено на 16 км югоизточно от гр. Котел в полите на Източна Стара планина. Селището се появява през XII-XIV век. През XVIII век се превръща в занаятчийски и културен център. Днес Жеравна е известен архитектурен резерват. В селото са запазени над 200 дървени къщи (всяка паметник на културата), строени по време на Възраждането. Някои от тях са на повече от 300 години. Запазен е автентичния възрожденски облик–тес [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HistoryAndCulture {
            get {
                return ResourceManager.GetString("HistoryAndCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Name&quot;:&quot;връх Вихрен&quot;,
        ///      &quot;Description&quot;:&quot;Връх първенец на Пирин планина, която се помества в Югозападна България, част от Рило-Родопския масив. Висок 2914 м., се нарежда на второ място по височина в страната и на трето на Балканския полуостров. Разположен е между реките Струма и Места. В района, в който се намира върха са разположени голяма част от езерата, образувани в планината. Единственно тук от цялата територия на страната вирее цветето еделвайс. Достъпен е откъм долината на Бъндерица [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Landmarks {
            get {
                return ResourceManager.GetString("Landmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Name&quot;:&quot;Ивановските скални църкви &quot;,
        ///      &quot;Description&quot;:&quot;Ивановските скални църкви се намират на 18 км. южно от град Русе. Отличават се от другите запазени скални манастирски комплекси в България с добре запазените си стенописи. \r\rЗа разлика от традиционните манастири, който се състоят от 1–2 църкви , монашеска и стопанска части, в Иваново има разклонена мрежа от малки скални църкви, параклиси и килии, издълбани на различна височина в скалите на живописния каньон на река Русенски лом и св [rest of string was truncated]&quot;;.
        /// </summary>
        public static string МonasteriesАndТemples {
            get {
                return ResourceManager.GetString("МonasteriesАndТemples", resourceCulture);
            }
        }
    }
}
